version: "3"
services:
  node:
    image: cmpsmarcio/desafio-aula1-helloworld
    build: .
    container_name: desafio-hello-world
    command: bash -c "npm install && npm start"
    restart: always
    ports: 
      - "8080:8080"